"""State shared between nodes in the TalentScout interview graph."""

from typing import TypedDict
from uuid import UUID


class InterviewState(TypedDict, total=False):
    """Data passed between the interview workflow's agents."""

    # Identifies the hiring job whose context is being used.
    job_id: UUID

    # Candidate's latest answer, when available.
    candidate_answer: str

    # Retrieved company/job-specific context.
    retrieved_context: list[str]

    # Question generated by the interviewer agent.
    current_question: str
