"""State shared between nodes in the TalentScout interview graph."""

from typing import TypedDict
from uuid import UUID

from talentscout.agents.answer_evaluation import AnswerEvaluation
from talentscout.agents.role_competency import RoleCompetencyAnalysis


class InterviewTurn(TypedDict):
    """Represent one completed question-and-answer exchange."""

    question: str
    candidate_answer: str
    evaluation: AnswerEvaluation

class InterviewState(TypedDict, total=False):
    """Data passed between interview workflow agents."""

    # Identifies the hiring job whose context is being used.
    job_id: UUID

    # The job description defines the skills and requirements being assessed.
    job_description: str

    # Candidate's latest answer, when available.
    candidate_answer: str

    # Structured evaluation of the candidate's latest answer.
    answer_evaluation: AnswerEvaluation    

    # Document text retrieved using semantic search.
    retrieved_context: list[str]

    # Question generated by the interviewer agent.
    current_question: str

    # Completed question-and-answer exchanges from the interview.
    interview_history: list[InterviewTurn]    

    # Optional Additional Interview Guidance supplied to role analysis.
    additional_guidance: list[str]

    # Structured competencies extracted from the JD and optional guidance.
    role_competency_analysis: RoleCompetencyAnalysis