"""State shared between nodes in the TalentScout interview graph."""

from typing import TypedDict
from uuid import UUID


class InterviewState(TypedDict, total=False):
    """Data passed between interview workflow agents."""

    # Identifies the hiring job whose context is being used.
    job_id: UUID

    # The job description defines the skills and requirements being assessed.
    job_description: str

    # Candidate's latest answer, when available.
    candidate_answer: str

    # Document text retrieved using semantic search.
    retrieved_context: list[str]

    # Question generated by the interviewer agent.
    current_question: str