"""add company context to jobs

Revision ID: d688fe14a740
Revises: 34633b62a618
Create Date: 2026-08-21 16:43:36.323062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d688fe14a740"
down_revision: str | Sequence[str] | None = "34633b62a618"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("company_context", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "company_context")
    # ### end Alembic commands ###
